version: "3.9"

services:
  db:
    image: postgres:15
    container_name: construction_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: construction_control
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: construction_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: construction_control
      DB_USER: postgres
      DB_PASSWORD: postgres
      # Добавляем адрес MediaMTX
      MEDIAMTX_HOST: http://localhost:8889
    ports:
      - "8088:8080"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: construction_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: construction_mediamtx
    restart: always

    # Пробрасываем порты, которые нужны (WebRTC, RTSP и т.д.)
    ports:
      - "8889:8889" # WebRTC (важно для вашего плеера)
      - "8554:8554" # RTSP
      - "8888:8888" # HLS
      - "1935:1935" # RTMP

    # Монтируем наш файл конфигурации
    volumes:
      - ./mediamtx.yml:/mediamtx.yml

    # ВАЖНО: Используем host сеть, чтобы контейнер видел вашу локальную камеру 192.168.0.103
    # Иначе Docker может не найти IP камеры внутри своей виртуальной сети.
    network_mode: host

volumes:
  pg_data: